# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LayoutDeploymentChecklistItems < Formula
  desc ""
  homepage "https://github.com/pranaybinju/layout-deployment-checklist-items"
  version "0.2.7"

  on_macos do
    url "https://github.com/pranaybinju/layout-deployment-checklist-items/releases/download/v0.2.7/layout-deployment-checklist-items_0.2.7_darwin_all.tar.gz"
    sha256 "08e5bd28bf7d1930f3d46944bec6d82c1c7b874c2cdc1e2c69cc5f9a4081bc38"

    def install
      bin.install "layout-deployment-checklist-items"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pranaybinju/layout-deployment-checklist-items/releases/download/v0.2.7/layout-deployment-checklist-items_0.2.7_linux_arm64.tar.gz"
      sha256 "f1597ecc20390467e1e8fc5da8e827e15e1cf0ada877abd7daf428692fac5038"

      def install
        bin.install "layout-deployment-checklist-items"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pranaybinju/layout-deployment-checklist-items/releases/download/v0.2.7/layout-deployment-checklist-items_0.2.7_linux_amd64.tar.gz"
      sha256 "eca25e8eba04c280ed695a3bd1a6374df77aabab0b26b66f329c5a59252bfc0a"

      def install
        bin.install "layout-deployment-checklist-items"
      end
    end
  end
end
